poll/urls.py

from django.urls import path
from . import views
app_name = 'polls'
urlpatterns = [
    
    # path('index/', views.index, name='index'),
    path('list/', views.list_poll, name='list'),
    path('<int:p_id>/', views.detailview, name='detail'),
    path('createPoll/', views.create_Poll, name='addPoll'),
    path('<int:p_id>/vote/', views.vote, name='vote'),
    
    
    path('addChoice/<int:p_id>/', views.add_choice, name='addChoice'),
    path('editchoice/<int:choice_id>/', views.choice_edit, name='editchoice'),
    path('choicedelete/<int:choice_id>/',views.choice_delete, name='choicedelete'),
     
    path('edit/<int:p_id>/', views. edit_poll, name='editPoll'),
    path('delete/<int:p_id>/', views.polls_delete, name='deletePoll'),
    
]

pollproject/urls.py
from django.contrib import admin
from django.urls import path,include
from Users.views import home

urlpatterns = [
    path('home/', home, name='home'),
    path('polls/', include('poll.urls')),
    path('users/', include('Users.urls')),
    path('admin/', admin.site.urls),
    
]

poll/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import secrets
# Create your models here.

class Poll(models.Model):
    owner = models.ForeignKey('Users.User', on_delete=models.CASCADE, default=1)
    poll_text = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.poll_text
    @property
    def get_vote_count(self):
        return self.vote_set.count()
    
    
    def get_result_dict(self):
        res = []
        for choice in self.choice_set.all():
            d = {}
            # alert_class = ['primary', 'secondary', 'success',
            #                'danger', 'dark', 'warning', 'info']

            
            #d['alert_class'] = secrets.choice(alert_class)
            d['text'] = choice.choice_text
            d['num_votes'] = choice.get_vote_count
            if not self.get_vote_count:
                d['percentage'] = 0
            else:
                d['percentage'] = (choice.get_vote_count /
                                   self.get_vote_count)*100

            res.append(d)
        return res    

class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text
    @property
    def get_vote_count(self):
        return self.vote_set.count()
    
    
class Vote(models.Model):
    user = models.ForeignKey('Users.User', on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.poll.poll_text[:15]} - {self.choice.choice_text[:15]} - {self.user.name}'
    

poll/forms.py
from django import forms
from .models import Poll, Choice


class PollAddForm(forms.ModelForm):

    choice1 = forms.CharField(label='Choice 1', max_length=100, min_length=1,
                              widget=forms.TextInput(attrs={'class': 'form-control'}))
    choice2 = forms.CharField(label='Choice 2', max_length=100, min_length=1,
                              widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Poll
        fields = ['poll_text', 'choice1', 'choice2']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'cols': 20}),
        }
        
class EditPollForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = ['poll_text']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'cols': 20}),
        }
        
        
class ChoiceAddForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text', ]
        widgets = {
            'choice_text': forms.TextInput(attrs={'class': 'form-control', })
        }

poll/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.contrib import messages
from django.http import HttpResponse
from .forms import PollAddForm, EditPollForm, ChoiceAddForm
from django.db.models import Count
from django.contrib.auth.decorators import login_required



# Create your views here.
from .models import *


# def index(request):
#     all_questions = Poll.objects.order_by('-pub_date')[:5]
#     context = {'all_questions': all_questions}
#     return render(request, 'index.html', context)

@login_required()
def detailview(request, p_id):
    
    poll = get_object_or_404(Poll, id=p_id)
    
    loop_count = poll.choice_set.count()
    print(loop_count)
    context = {
        'poll': poll,
        'loop_time': range(0, loop_count),
    }
    return render(request, 'polls/detail.html', context)

@login_required()
def create_Poll(request):
        if request.method == 'POST':
            form = PollAddForm(request.POST)
            if form.is_valid:
                poll = form.save(commit=False)
                poll.owner = request.user
                poll.save()
                new_choice1 = Choice(
                    poll=poll, choice_text=form.cleaned_data['choice1']).save()
                new_choice2 = Choice(
                    poll=poll, choice_text=form.cleaned_data['choice2']).save()

                messages.success(
                    request, "Poll & Choices Created successfully.", extra_tags='alert alert-success alert-dismissible fade show')

                return redirect('polls:list')
        else:
            form = PollAddForm()
            context = {
                'form': form,
            }
            return render(request, 'polls/create_poll.html', context)

@login_required()
def list_poll(request):
    
    all_polls = Poll.objects.all()  
    print(all_polls)
    context = {
        'polls': all_polls
    }
    return render(request, 'polls/poll_list.html', context)

@login_required()
def vote(request, p_id):
    poll = get_object_or_404(Poll, pk=p_id)
    choice_id = request.POST.get('choice')
    
    if choice_id:
        choice = Choice.objects.get(id=choice_id)
        vote = Vote(user=request.user, poll=poll, choice=choice)
        vote.save()

        return render(request, 'polls/result.html', {'poll': poll})
    else:
        messages.error(
            request, "No choice selected!", extra_tags='alert alert-warning alert-dismissible fade show')
        return redirect("polls:detail", p_id)
    
    
    
def edit_poll(request, p_id):
    
    poll_instance = get_object_or_404(Poll, pk=p_id)
    
    if request.method == 'POST':
        form = EditPollForm(request.POST, instance=poll_instance)
        if form.is_valid:
            form.save()
            messages.success(request, "Poll Updated successfully.",
                             extra_tags='alert alert-success alert-dismissible fade show')
            return redirect("polls:list")
            #return redirect('list')

    else:
        form = EditPollForm(instance=poll_instance)

    return render(request, "polls/edit_poll.html", {'form': form, 'poll': poll_instance})

@login_required()
def polls_delete(request, p_id):
    poll = get_object_or_404(Poll, pk=p_id)
    if request.user != poll.owner:
        return redirect('home')
    poll.delete()
    messages.success(request, "Poll Deleted successfully.",
                     extra_tags='alert alert-success alert-dismissible fade show')
    return redirect("polls:list")

@login_required
def add_choice(request, p_id):
    poll = get_object_or_404(Poll, pk=p_id)

    if request.method == 'POST':
        form = ChoiceAddForm(request.POST)
        if form.is_valid:
            new_choice = form.save(commit=False)
            new_choice.poll = poll
            new_choice.save()
            messages.success(
                request, "Choice added successfully.", extra_tags='alert alert-success alert-dismissible fade show')
            return redirect('polls:editPoll', poll.id)
    else:
        form = ChoiceAddForm()
    context = {
        'form': form,
    }
    return render(request, 'polls/add_choice.html', context)



@login_required
def choice_edit(request, choice_id):
    choice = get_object_or_404(Choice, pk=choice_id)
    poll = get_object_or_404(Poll, pk=choice.poll.id)
    
    if request.method == 'POST':
        form = ChoiceAddForm(request.POST, instance=choice)
        if form.is_valid:
            new_choice = form.save(commit=False)
            new_choice.poll = poll
            new_choice.save()
            messages.success(
                request, "Choice Updated successfully.", extra_tags='alert alert-success alert-dismissible fade show')
            print(poll.id)
            return redirect('polls:editPoll', poll.id)
    else:
        form = ChoiceAddForm(instance=choice)
    context = {
        'form': form,
        'edit_choice': True,
        'choice': choice,
    }
    return render(request, 'polls/add_choice.html', context)

@login_required
def choice_delete(request, choice_id):
    choice = get_object_or_404(Choice, pk=choice_id)
    poll = get_object_or_404(Poll, pk=choice.poll.id)
    choice.delete()
    messages.success(
        request, "Choice Deleted successfully.", extra_tags='alert alert-success alert-dismissible fade show')
    return redirect('polls:editPoll', poll.id)
    

poll/templates/polls/add_Choice.html
{% extends 'main.html' %}
{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            {% if edit_choice %}
            <h2>Update choice</h2>
            {% else %}
            <h2>Add new choice</h2>
            {% endif %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                {% if edit_choice %}
                <button type="submit" class="btn btn-primary" aria-label="Update choice">Update</button>
                <button type="button" class="btn btn-danger" onclick="if(confirm('Are you sure you want to delete this?')) { window.location.href='{% url 'polls:choicedelete' choice.id %}'; }" aria-label="Delete choice">Delete</button>
                {% else %}
                <button type="submit" class="btn btn-primary" aria-label="Add new choice">Add</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

poll/templates/polls/create_poll.html
{% extends 'main.html' %}
{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            <h2>Create new poll</h2>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Add Poll</button>
                <button type="button" class="btn btn-warning" 
                        onclick="window.location.href='{% url 'polls:list' %}'">Back</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

poll/templates/polls/detail.html
{% extends 'main.html' %}
{% block content %}
    <div class="container">
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <hr>
        <h2 class="mt-3 mb-3">{{ poll }}</h2>
        <form action="{% url 'polls:vote' poll.id %}" method="POST">
            {% csrf_token %}
            {% for choice in poll.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
            <br>
            {% endfor %}
            <input type="submit" value="Vote" class="btn btn-primary mt-3">
            <a class="btn btn-warning mt-3" href="{% url 'polls:list' %}" role="button">Cancel</a>
        </form>

    </div>

{% endblock content %}

poll/templates/polls/edit_poll.html
{% extends 'main.html' %}

{% block content %}
<div class="container">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            <h2>Edit poll</h2>
            {% if messages %}
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Update</button>
                <a class="btn btn-danger" href="{% url 'polls:deletePoll' poll.id %}" role="button" onclick="return confirm('Are you sure?')">Delete</a>
                <a class="btn btn-warning" href="{% url 'polls:addChoice' poll.id %}" role="button">Add Choice</a>
            </form>

            <div class="choices">
                <h2 class="text-center mt-3">Choices</h2>
                <hr>
                <ul class="list-group">
                    {% for choice in poll.choice_set.all %}
                    <li class="list-group-item"><a href="{% url 'polls:editchoice' choice.id %}"><i class="fas fa-pencil-alt"></i></a>&nbsp
                        {{ choice.choice_text }}</li>
                    {% endfor %}
                </ul>
            </div> 

        </div>
    </div>
</div>
{% endblock %}

poll/templates/polls/poll_list.html
{% extends 'main.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-sm-2">
            <h1 class="text-center mt-3 mb-3">Welcome to Polls List!</h1>
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <button type="button" class="btn btn-primary mb-4 float-right-up" 
                    onclick="window.location.href='{% url 'polls:addPoll' %}'" 
                    aria-label="Add Poll">
                Add Poll <i class="fas fa-plus"></i>
            </button>
            <ul class="list-group">
                {% for poll in polls %}
                <li class="list-group-item">
                    <a href="{% url 'polls:detail' poll.id %}">{{ poll.poll_text|truncatewords:5 }}</a>
                    {% if request.user == poll.owner %}
                    <button type="button" class="btn btn-primary btn-sm float-right mr-1" 
                            onclick="window.location.href='{% url 'polls:editPoll' poll.id %}'" 
                            aria-label="Edit Poll">
                        <i class="fas fa-pencil-alt"></i>
                    </button>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
            {% comment %}
            <nav class="mt-3">
                <ul class="pagination">
                    {% if polls.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1&{{ params }}">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ polls.previous_page_number }}&{{ params }}">Previous</a>
                    </li>
                    {% endif %}
                    <li class="page-item active">
                        <a class="page-link" href="">{{ polls.number }}</a>
                    </li>
                    {% if polls.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ polls.next_page_number }}&{{ params }}">Next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ polls.paginator.num_pages }}&{{ params }}">Last</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endcomment %}
        </div>
    </div>
</div>
{% endblock %}

poll/templates/polls/result.html
{% extends 'main.html' %}

{% block content %}
<div class="container">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <div id="piechart"></div>
    <div class="row">
        <div class="col-md-8 offset-sm-2">
            {% if poll.active %}
            <h3 class="mt-3 mb-3 text-center">Result for: {{ poll.poll_text }}</h3>
            {% else %}
            <h3 class="mt-3 mb-3 text-center">"{{ poll.poll_text }}" Has Ended Polling !</h3>
            {% endif %}
            <h3 class="mb-2 text-center">Total: {{ poll.get_vote_count }} votes</h3>
            <!-- progress bar -->
            <div class="progress mt-3 mb-2">
                {% for choice in poll.get_result_dict %}
                <div class="progress-bar progress-bar-striped active-{{ choice.alert_class }}" role="progressbar" style="width: {{ choice.percentage }}%;"
                    aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"><b>
                        {{choice.text|truncatewords:2}}-{{choice.percentage|floatformat}}%</b>
                </div>
                {% endfor %}

            </div>
            <ul class="list-group">
                {% for choice in poll.choice_set.all %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{ choice.choice_text }}
                    <span class="badge badge-primary badge-pill">{{ choice.get_vote_count }}</span>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            <a class="btn btn-primary mt-3" href="{% url 'polls:list' %}" role="button">Back To Polls</a>
            
        </div>

    </div>
</div>

{% endblock content %}

