Users/urls.py
from django.urls import path
from Users.views import (
            home,
            login_view,
            logout_view,
            registration_view,
        )
        
app_name = 'users'       
urlpatterns  = [
    path('home/',home, name="home"),
    path('register/',registration_view, name="register" ),
    path('logout/',logout_view, name="logout" ),
    path('login/',login_view, name="login" )
]

poll/urls.py

from django.urls import path
from . import views
app_name = 'polls'
urlpatterns = [
    
    # path('index/', views.index, name='index'),
    path('list/', views.list_poll, name='list'),
    path('<int:p_id>/', views.detailview, name='detail'),
    path('createPoll/', views.create_Poll, name='addPoll'),
    path('<int:p_id>/vote/', views.vote, name='vote'),
    
    
    path('addChoice/<int:p_id>/', views.add_choice, name='addChoice'),
    path('editchoice/<int:choice_id>/', views.choice_edit, name='editchoice'),
    path('choicedelete/<int:choice_id>/',views.choice_delete, name='choicedelete'),
     
    path('edit/<int:p_id>/', views. edit_poll, name='editPoll'),
    path('delete/<int:p_id>/', views.polls_delete, name='deletePoll'),
    
]

pollproject/urls.py
from django.contrib import admin
from django.urls import path,include
from Users.views import home

urlpatterns = [
    path('home/', home, name='home'),
    path('polls/', include('poll.urls')),
    path('users/', include('Users.urls')),
    path('admin/', admin.site.urls),
    
]

templates/index.html
{% extends 'main.html' %}

{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div id="home-content">
                <h1>Polling- Get Started here! Gopal Ghule..argocd:demo:19th feb !!!</h1>
                <hr>
                <a class="btn btn-light btn-lg" href="{% url 'polls:list' %}" role="button">
                    click Here TO Get Started !</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Poll Me | Polls List</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
        crossorigin="anonymous">

    {% block custom_css %}{% endblock custom_css %}

</head>

<body>
    {% include 'navbar.html' %}

    {% block content %}

    {% endblock content %}


    <!-- All javascript files goes under here    -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>

</html>

templates/navbar.html
<div class="container-fluid">
    <nav class="navbar navbar-expand-md navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Polls-Applicationn</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'users:home' %}">Home <span class="sr-only">(current)</span></a>
              </li>
                {% if request.user.is_authenticated %}
              <li class="nav-item">
                    <a class="nav-link" href="{% url 'polls:list' %}">Poll</a>
              </li>
                {% endif %}
          </ul>
          <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
              <li class="nav-item-active">
                  <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
              </li>
            {% else %}
                <a class="nav-link" href="{% url 'users:login' %}">SignI</a>
                <a class="nav-link" href="{% url 'users:register' %}">SignUp</a>
            {% endif %}
  
          </ul>
      </div>
  </nav





